apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy525
  labels:
    app: autodeploy525
  namespace: namespace-workflow-1716316313394
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy525
  template:
    metadata:
      labels:
        app: autodeploy525
    spec:
      containers:
        - name: autodeploy525
          image: acrworkflow1716316313394.azurecr.io/image-workflow-1716316313394:latest
          ports:
            - containerPort: 5000